sudo: required
services:
  - docker

before_install:
  # Cài đặt các phần phụ thuộc và xây dựng Docker image
  - docker build -t haisoftwarevn/docker-react -f Dockerfile.dev . 

  # Cập nhật gem-wrappers
  - gem uninstall gem-wrappers || true  # Bỏ qua lỗi nếu không thể gỡ cài đặt
  - gem install gem-wrappers

script:
  # Chạy các kiểm tra bằng Docker
  - docker run -e CI=true haisoftwarevn/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-904233134612"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

