sudo: required
services:
  - docker

before_install:
  - docker build -t haisoftwarevn/docker-react -f Dockerfile.dev . 
  - if gem list gem-wrappers -i; then gem uninstall gem-wrappers --force; fi
  - gem install gem-wrappers

script:
  - docker run -e CI=true haisoftwarevn/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-904233134612"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

