FROM node:18

WORKDIR '/app'

COPY package.json .

RUN apt-get update && apt-get install -y software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get update && apt-get install -y libc6

RUN npm install

COPY . .

CMD [ "npm","run","start" ]